#!/usr/bin/perl
use strict;
use List::Util qw(sum);
use FindBin qw($RealBin);
use lib "$RealBin/../lib";
use Max;
use Net::Graphite;

my $graphite = Net::Graphite->new;

my $max = Max->connect(Max->discover);

for my $room ($max->rooms) {
    my $name = $room->name || $room->id;
    my $valves = sum map $_->valve, grep $_->has_valve, $room->devices;
    $graphite->send(path => "max.$name.temperature", value => $room->temperature);
    $graphite->send(path => "max.$name.setpoint", value => $room->setpoint);
    $graphite->send(path => "max.$name.valves", value => $valves);
}
$graphite->send(path => "max.boiler", value => 0 + $max->heat_demand);
